### ISSUE TITLE
How to prevent @trpc/server from leaking to client?

### ISSUE THREAD

**Issue by Serpentarius13** [ottomated/trpc-svelte-query#16]
When using this cool library with @trpc/server together in one full-stack SvelteKit app, I encountered an issue where it is not possible to use client `trpc` without using `isServer: true` option when creating a server. How do I abstract @trpc/server from client so that it doesnt load with bundle? Thanks

**Comment by ottomated** [comment]
Please post a minimal reproduction

**Comment by Serpentarius13** [comment]
> Please post a minimal reproduction

Hey, sorry for late reply. Everything works fine now. Thanks for the lib!
