### ISSUE TITLE
Using package without @trpc/client doesn't work

### ISSUE THREAD

**Issue by Serpentarius13** [ottomated/trpc-svelte-query#17]
When using a package without installing @trpc/client package alongside, the code doesnt work and the package doesnt re-export httpBatchLink. Perhaps it would be better to use it as peer-dependency then?

**Comment by ottomated** [comment]
It is a peer dependency already

**Comment by Serpentarius13** [comment]
> It is a peer dependency already

My bad, it seems I removed it after installing library >< Sorry
