### ISSUE TITLE
Optional parent from types in order to correctly use `ssr` in SvelteKit Actions

### ISSUE THREAD

**Issue by Giggiux** [ottomated/trpc-svelte-query#4]
_Premise: This is the first time I'm using trpc with svelte, so maybe I'm doing something wrong conceptually, but the change seems almost harmless._

While using `trpc-svelte-query` in server `actions`, trying to use `ssr` in order to do internal calls to trpc results in this TS error:

```
Argument of type 'RequestEvent<RouteParams, "/dashboard">' is not assignable to parameter of type 'SveltekitRequestEventInput'.
  Property 'parent' is missing in type 'RequestEvent<RouteParams, "/dashboard">' but required in type 'SveltekitRequestEventInput'.
  ```

After a very quick look at the code I believe `parent` is never used anywhere, so seems like it's there just to have pure SvelteKit type compatibility.

Here is where it's defined:
https://github.com/ottomated/trpc-svelte-query/blob/d64e9767340e7743b0f36ccda6336024bf1527ee/src/ssr/index.ts#L14
https://github.com/ottomated/trpc-svelte-query/blob/d64e9767340e7743b0f36ccda6336024bf1527ee/src/ssr/index.ts#L23

By making it optional, TS doesn't complain anymore when passing the `event` from the `actions` handlers.

If this seems like a decent solution that isn't harmless, I can _very easily_ do a PR with the changes! :)

**Comment by ottomated** [comment]
I'm using sveltekit types directly in the upcoming version, so this should be solved.
