### ISSUE TITLE
Using 1.0.0 createContext is not awaited

### ISSUE THREAD

**Issue by JonathonRP** [ottomated/trpc-svelte-query#5]
When attempting to access ctx without (await ctx) properties return undefined and typescript thinks it's an object instead of promise...
Looking for help to resolve this.

**Comment by ottomated** [comment]
Please post a minimal reproducible example using stackblitz or codesandbox.

**Comment by JonathonRP** [comment]
I just followed the example -
import type { inferAsyncReturnType } from "@trpc/server"; 
  
 export const createContext = async (event: RequestEvent) => { 
         return { 
                 event 
         } 
 }; 
  
 export type Context = inferAsyncReturnType<typeof createContext>;

Which if followed creates this issue, simply removing async fixes this. Also the example docs for creating server needs createContext line.

**Comment by ottomated** [comment]
A minimal reproducible example should contain all the code needed to reproduce the error and no more. You can create one [here](https://codesandbox.io/s/). Without that, I can't help you.

**Comment by JonathonRP** [comment]
@ottomated fyi working on reproduction repo from the provided link

**Comment by ottomated** [comment]
Okay, closing this issue until you post a non-working version 👍

**Comment by JonathonRP** [comment]
@ottomated - [repo](https://codesandbox.io/p/sandbox/friendly-blackburn-vzrdxn?file=%2Fsrc%2Froutes%2F%28app%29%2F%2Blayout.svelte%3A24%2C6)

**Comment by ottomated** [comment]
This is fixed in 1.0.1
